theme: jekyll-theme-minimal
title: Matt MacDermott
description: PhD Student at Imperial College London in the Centre for Doctoral Training in Safe and Trusted AI. Member of the Causal Incentives Working Group.
google_analytics: G-ES2SYVSDLM