theme: jekyll-theme-minimal
title: Matt MacDermott
description: PhD Student at Imperial College London, [Centre for Doctoral Training in Safe and Trusted AI](https://safeandtrustedai.org/). Member of the [Causal Incentives Working Group](https://causalincentives.net/). mjm121 at ic.ac.uk
google_analytics: G-ES2SYVSDLM
logo: profilepic.png
