theme: jekyll-theme-minimal
title: Matt MacDermott
description: AI safety researcher, [LawZero](lawzero.org). PhD Student at Imperial College London, [CDT in Safe and Trusted AI](https://safeandtrustedai.org/). Also involved in the [Causal Incentives Working Group](https://causalincentives.net/). mjm121 at ic.ac.uk
google_analytics: G-ES2SYVSDLM
logo: profilepic.png
