theme: jekyll-theme-minimal
title: Matt MacDermott
description: PhD Student at Imperial College London, [CDT in Safe and Trusted AI](https://safeandtrustedai.org/). Working on the [Safe AI for Humanity](https://yoshuabengio.org/2023/05/07/ai-scientists-safe-and-useful-ai/) Project. Also involved in the [Causal Incentives Working Group](https://causalincentives.net/). mjm121 at ic.ac.uk
google_analytics: G-ES2SYVSDLM
logo: profilepic.png
