theme: jekyll-theme-minimal
title: Matt MacDermott
description: PhD Student at Imperial College London as part of the Centre for Doctoral Training in Safe and Trusted AI. Member of the Causal Incentives Working Group.
google_analytics: G-ES2SYVSDLM
logo: profilepic.png
